### Get status

http://localhost:4500/currency-rates/test


### Get coingate current

http://localhost:4500/currency-rates/coingate


### Get cbrf current

http://localhost:4500/currency-rates/cbrf


### Get cbrf specific date

http://localhost:4500/currency-rates/cbrf?date=2024-10-01



### Get OpenExchangeRates current

http://localhost:4500/currency-rates/oer


### Get OpenExchangeRates specific date
http://localhost:4500/currency-rates/oer?date=2024-09-17


### testRoutes

http://localhost:4500/
